### ISSUE TITLE
Switch Control and Switch State topics inverted

### ISSUE THREAD

**Issue by louisr0608** [oerkel47/OctoPrint-MQTT-for-PSUcontrol#2]
The Switch Control and Switch State topic fields appear to work inverted to what's expected.

In my setup:
Switch control topic - sonoff/relay/1/set
Switch state topic - sonoff/relay/1
ON message - 1
OFF message - 0

When configured as above, instructing PSU Control to turn on the relay sends out the message
sonoff/relay/1 1
which is a status message, and does not trigger the switch to turn on.

If I invert the two fields in the configuration page, as below, it works as expected:
Switch control topic - sonoff/relay/1
Switch state topic - sonoff/relay/1/set

**Comment by oerkel47** [comment]
Hi,

What you describe is not a bug. 

To quote from the plugin page:

> 
> What it does not
> 
>     This plugin is not meant to control any other switch except the one configured in PSUControl.

This means:
- the switch **must** be controlled by the PSU Control plugin itself
- MQTT-for-PSUcontrol does **not** directly control an external switch _(this is what you are trying to do)_
- MQTT-for-PSUcontrol can control PSU Control and update your MQTT topics

[If you want to control an external switch via MQTT you dont really need the PSU Control plugin.
Take a look at this plugin instead, I think it does what you are trying to do.](https://plugins.octoprint.org/plugins/tasmota_mqtt/)

**Comment by louisr0608** [comment]
Thank you! Apologies for misunderstanding the intent of this plugin. I appreciate you taking the time to find another plugin that would suit my needs.
