### ISSUE TITLE
Use same device discovery setting as HomeAssistant Discovery plugin

### ISSUE THREAD

**Issue by Sebclem** [oerkel47/OctoPrint-MQTT-for-PSUcontrol#3]
Hi,

I don't know if it's possible, but this can be interesting if we can have the save device ID and other stuff as the [HomeAssistant Discovery](https://github.com/cmroche/OctoPrint-HomeAssistant) so we can have the PSU switch on the same "device" in home assistant.

**Comment by oerkel47** [comment]
Hi. I can add a feature to edit the ID etc. That's no problem. I am not sure if this can mess up the other plugin though, I will do some testing.

**Comment by oerkel47** [comment]
I just released a new version which makes this possible! Check out the options, there should be enough explanation.

**Comment by Sebclem** [comment]
Perfect ! Worked like a charm ! 
Thank you 🎉

**Comment by oerkel47** [comment]
You are welcome, thanks for feedback :)
